// import type { Metadata } from "next";

import Header from "@/components/FlyghtOption/Header/Header";
import "./../../styles/Flyght/mainFly.scss";
import "./../../styles/Hotel/hotel.scss";
import "./../../styles/Favourites/favourites.scss";
import FooterMain from "@/components/Landing/Footer/FooterMain";
import TanStackProvider from "@/providers/TanStackProvider";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };

export const metadata = {
  title: {
    absolute: "sema velesik",
    template: "%s | sema velesik",
  },
  description: "site by sema velesik",
  applicationName: "sema velesik",
  authors: [
    {
      name: "sema velesik",
      url: "http://localhost:3000",
    },
  ],
  publisher: "sema velesik",
  icons: {
    // короткий путь до иконки shortcut: '',
    // обычный путь до иконки icon: '',
    // какая иконка будет у приложения в apple(PWA) apple: ''
  },
  // разметка для соц.сетей
  openGraph: {
    title: "sema velesik",
    description: "site by sema velesik",
    type: "website",
    locale: "ru_Ru",
    siteName: "TourTravel",
  },
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackProvider>
      <Header />
      <main>
        <div id="modal"></div>
        {children}
      </main>
      <FooterMain />
    </TanStackProvider>
  );
}
