// import type { Metadata } from "next";

import './../../styles/Account/header-account.scss';
import FooterMain from "@/components/Landing/Footer/FooterMain";
import HeaderAccount from "@/components/Account/Header/HeaderAccount";
import Header from '@/components/FlyghtOption/Header/Header';
import TanStackProvider from '@/providers/TanStackProvider';

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };

export default function MainLayout({ children }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    // <TanStackProvider>
    <>
        <Header />
        <main>
            {children}
        </main>
        <FooterMain />
        </>
    // </TanStackProvider>
  );
}